accounts/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView

from accounts import views


urlpatterns = patterns('',
    url(r'^$', views.NewUserView.as_view(), name='register'),
    url(r'^success/$', TemplateView.as_view(template_name="accounts/success.html"), name='success_created'),
    url(r'^activate/(?P<activation_key>\w+)/$', views.activate),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^login/$', views.LogInView.as_view(), name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^home/$', views.HomeView.as_view(), name='home'),
    url(r'^edit_user/$', views.edit_user_view, name='edit_user'),
)

places/urls.py
from django.conf.urls import patterns, url

from places import views


urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.PlaceDetailView.as_view(), name='place_detail'),
    url(r'^creat_new_place/$', views.NewPlaceCreateView.as_view(), name='creat_new_place'),
    )

sandbox/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'), 
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^places/', include('places.urls', namespace='places'))
)

accounts/models.py
import datetime

from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser
from django.utils import timezone


class UserManager(BaseUserManager):
    def _create_user(self, email, password, active, staff, superuser,
                       **extra_fields):
        now = timezone.now()
        email = self.normalize_email(email)
        user = self.model(email=email, staff=staff, active=active,
                          superuser=superuser, register_date=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        return self._create_user(email, password, False, False, False,
                                 last_login=datetime.datetime.now(), **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        user=self._create_user(email, password, True, True, True, **extra_fields)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):

    GENDER = ((1, 'Female'), (2, 'Male'))

    email = models.EmailField(max_length=100, unique=True)
    name = models.CharField(max_length=50)
    surname = models.CharField(max_length=50)
    gender = models.IntegerField(choices=GENDER, default=1)
    telephone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    register_date = models.DateTimeField(auto_now=False, auto_now_add=True)
    register_updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    activation_key = models.CharField(max_length=40, default='')
    date_of_birth = models.DateTimeField(null=True)
    akey_expires = models.DateTimeField(default=lambda: timezone.now()
                                        + datetime.timedelta(2))
    active = models.BooleanField(default=False)
    staff = models.BooleanField(default=False)
    superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __unicode__(self):
        return '{} {}'.format(self.name, self.surname)

    @property
    def get_email(self):
        return self.email

    def get_short_name(self):
        return self.name

    @property
    def is_superuser(self):
        return self.superuser

    @property
    def is_staff(self):
        return self.superuser

    def has_perm(self, perm, obj=None):
        return self.superuser

    def has_module_perms(self, app_label):
        return self.superuser

    def get_last_login(self):
        return self.last_login

accounts/forms.py
from django import forms

from accounts.models import User


class NewUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'email',
            'password',
            'name',
            'surname',
            'gender',
            'telephone_number',
            'address',
        ]
        widgets = {'password': forms.PasswordInput()}


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            'name',
            'surname',
            'gender',
            'telephone_number',
            'address',
        ]


class LogInForm(forms.Form):
    email = forms.CharField(max_length=200)
    password = forms.CharField(widget=forms.PasswordInput())
    widgets = {'password': forms.PasswordInput()}


class UserPasswordChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['password']

    new_password_1 = forms.CharField(max_length=30, min_length=8)
    new_password_2 = forms.CharField(max_length=30, min_length=8)


class UserEmailChangeForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email']

accounts/views.py
import random, sha

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.shortcuts import (
    get_object_or_404,
    render_to_response,
    render,
    redirect,
)
from django.utils import timezone
from django.views import generic


from accounts.forms import NewUserForm, LogInForm, EditUserForm
from accounts.models import User
from sandbox.settings import EMAIL_HOST_USER, HOST_NAME


class NewUserView(generic.CreateView):
    template_name = "accounts/new_account.html"
    success_url = reverse_lazy('accounts:success_created')
    form_class = NewUserForm

    def form_valid(self, form):
        new_user = form.save()
        new_user.set_password(form.cleaned_data["password"])
        salt = sha.new(str(random.random())).hexdigest()[:5]
        new_user.activation_key = sha.new(salt+new_user.name).hexdigest()
        new_user.save()
        subject = "SandboxApp: Confirm registration"
        text = "Hi %s, \n please confirm Your registration by clicking or copy-past this link \n" \
               "%s/accounts/activate/%s/ \n Please confirm with in 48 houers. Thank You for using our app."\
                " \n Your Sandbox Team" % (new_user.name, HOST_NAME, new_user.activation_key)
        send_mail(subject, text, EMAIL_HOST_USER, [new_user.email], fail_silently=False)
        return super(NewUserView, self).form_valid(form)


def activate(request, activation_key):
    profile = get_object_or_404(User, activation_key=activation_key)
    if profile.akey_expires < timezone.now():
        return render_to_response('accounts/activate.html', {'expired': True})
    profile.save(update_fields=['active', 'activation_key'])
    return render_to_response('accounts/activate.html', {'success': True})


class LogInView(generic.FormView):
    template_name = "accounts/login.html"
    form_class = LogInForm

    def form_valid(self, form):
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        user = authenticate(email=email, password=password)
        if user.active:
            login(self.request, user)
        return redirect('accounts:home')


@login_required()
def edit_user_view(request):
    template_name = "accounts/edit_user.html"
    form = EditUserForm(request.POST or None, instance=request.user)
    if form.is_valid():
        form.save()
        return redirect('accounts:edit_user')
    return render(request, template_name, {'form': form})


class HomeView(generic.ListView):
    template_name = 'accounts/home.html'
    context_object_name = 'User_list'
    model = User


def logout_view(request):
    logout(request)
    return redirect('accounts:home')

accounts/templates/accounts/_base.html
      {% if user.is_authenticated %}
          Welcome <code>{{ user.name }}</code>! Click to  <a href="{% url 'accounts:logout' %}">Logout</a>
      {% else %}
          Please log in <a href="{% url 'accounts:login' %}">here</a> or <a href="{% url 'accounts:register' %}">Register</a>
      {% endif %}

      <br>
<a href="{% url 'accounts:edit_user' %}">Edit User</a>


      {% block contents %}
      {% endblock %}

accounts/templates/accounts/activate.html
{% extends "accounts/_base.html" %}

{% block contents %}

    <h1>Aktywacja konta zakończona powodzeniem. GRATULUJEMY!!!</h1>

{% endblock %}

accounts/templates/accounts/edit_user.html
{% extends "accounts/_base.html" %}

{% block contents %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save" />
    </form>

{% endblock %}

accounts/templates/accounts/home.html
{% extends "accounts/_base.html" %}

{% block contents %}

    <h1>To jest Strona Domowa</h1>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "accounts/_base.html" %}

{% block contents %}
    {% if user.is_authenticated %}
        <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
    {% else %}
        {% if form.errors %}
            <p>Your username and password didn't match. Please try again.</p>
        {% endif %}

        <form action="" method="post">
            {% csrf_token %}
            <p>{{ form.as_p }}</p>

            <input type="submit" value="login" />
        </form>

    {% endif %}
{% endblock %}

accounts/templates/accounts/logout.html
{% extends "accounts/_base.html" %}

{% block content %}
<p>Logged out</p>
{% endblock %}

accounts/templates/accounts/new_account.html
{% extends "accounts/_base.html" %}

{% block contents %}
<div id="newProfile">
	<br><br>
	<div id="titleNewProfile">
		<p>Formularz tworzenia nowego użytkownika</p>
	</div>	
	<br>
	<div id="descriptionNewProfile">
		<p>Wypełnij poniższe pola a następnie kliknij "Utwórz"</p>
	</div>

</div>


    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Utwórz" />
    </form>


{% endblock %}

accounts/templates/accounts/success.html
{% extends "accounts/_base.html" %}

{% block contents %}

    <h1>Gratulacje!!! Twoje konto w Piaskownicy zostało utworzone. Dokonaj aktywacji przez link wysłany na e-mail</h1>

{% endblock %}