places/urls.py
from django.conf.urls import patterns, url

from places import views


urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.PlaceDetailView.as_view(), name='place_detail'),
    url(r'^creat_new_place/$', views.NewPlaceCreateView.as_view(), name='creat_new_place'),
    )

sandbox/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', TemplateView.as_view(template_name='index.html'), name='home'), 
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^places/', include('places.urls', namespace='places'))
)

places/models.py
from django.db import models

from easy_maps.geocode import google_v3 as geocode

from django.utils.encoding import force_text

class Place(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=450)
    address_country = models.CharField(max_length=60)
    address_city = models.CharField(max_length=60)
    address_street = models.CharField(max_length=120)
    address_post_code = models.CharField(max_length=8)
    date_created = models.DateTimeField(auto_now=False, auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    latitude = models.DecimalField(default=0, max_digits=16, blank=True,
                                   decimal_places=8)
    longitude = models.DecimalField(default=0, max_digits=16, blank=True,
                                    decimal_places=8)

    def __unicode__(self):
        return self.name

    def get_full_address(self):
        """
        create string with full address
        """
        return force_text(self.address_country) + \
               ", " + force_text(self.address_city) + \
               ", " + force_text(self.address_street)

    def fill_geocode(self):
        new_geocode = geocode(self.get_full_address())
        self.latitude = new_geocode[0]
        self.longitude = new_geocode[1]

    def save(self, *args, **kwargs):
        # self.fill_geocode()
        super(Place, self).save(*args, **kwargs)

places/forms.py
from django import forms

from places.models import Place


class NewPlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = [
            'name',
            'description',
            'address_country',
            'address_city',
            'address_street',
            'address_post_code',
            ]

places/views.py
from django.core.urlresolvers import reverse_lazy
from django.views import generic

from places.models import Place
from places.forms import NewPlaceForm

class IndexView(generic.ListView):
    template_name = 'places/index.html'
    context_object_name = 'place_list'
    model = Place


class PlaceDetailView(generic.DetailView):
    template_name = 'places/place_detail.html'
    model = Place

class NewPlaceCreateView(generic.CreateView):
    template_name = "places/create_new_place.html"
    success_url = reverse_lazy('places:creat_new_place')
    form_class = NewPlaceForm

    def form_valid(self, form):
        new_place = form.save()
        new_place.save()
        return super(NewPlaceCreateView, self).form_valid(form)

places/templates/places/_base.html
<!-- extends 'foundation/base.html' -->

{% block contents %}

{% endblock %}

places/templates/places/create_new_place.html
{% extends "accounts/_base.html" %}

{% block contents %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create" />
    </form>


{% endblock %}

places/templates/places/index.html
{% extends "places/_base.html" %}

{% block contents %}

    <ul>
        {%  for place in place_list %}
            <li><a href="{% url 'places:place_detail' place.pk %}">{{ place.name }}</a> </li>
        {% endfor %}
    </ul>

{% endblock %}

places/templates/places/place_detail.html
{% extends "places/_base.html" %}

{% load easy_maps_tags %}

{% block contents %}

    <h1>{{ place.name }}</h1>
    <h5>Added on:{{ place.date_created }}</h5>
    <h3>Description:
        {{ place.description }}
        <b>Address:</b></h3>
    <h3>{{ place.address_street }}</h3>
    <h3>{{ place.address_post_code }} {{ place.address_city }}</h3>

    {% easy_map place.get_full_address 400 400 %}
{% endblock %}